name: Terraform Deployment

on:
  push:
    branches:
      - main  # Change to your target branch

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change to your AWS region

      - name: Initialize Terraform
        run: terraform init

      - name: terraform
        run : terraform fmt

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan 

      - name: Apply Terraform
        run: terraform apply --auto-approve 
